### ISSUE TITLE
Tracking issue

### ISSUE THREAD

**Issue by druskus20** [druskus20/volym#1]
- [ ] Add parameters to the compute shader
- [ ] Dynamically load volumes 
- [ ] Support multiple rendering algorithms
- [ ] Implement a simple volume renderer
- [ ] Add an option to flip the volume
- [ ] Support segmented volumesç
- [ ] Implement importance driven volume rendering
